config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help" => "static_pages#help"
  delete "logout" => "users/sign_out"

  devise_for :users, path: "", path_name: {sign_out: "logout"}, controllers: {
    sessions: "custom_devise/sessions"
  }

  namespace :admin do
    root "dashboard#show"
    resources :skills
    resources :positions
    resources :users
    resources :projects
    resources :teams
  end

  resources :users
  resources :projects, only: :show
  resources :teams, only: [:index, :show]
  resources :activities, only: :index
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  before_save :set_default_value

  belongs_to :user

  private
  def set_default_value
    self.time = Time.zone.now
  end
end

app/models/position.rb
class Position < ActiveRecord::Base
  has_many :user_positions
  has_many :users, through: :user_positions
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :project_users
  has_many :members, class_name: "User", through: :project_users, source: :user
  belongs_to :team
  belongs_to :leader, class_name: "User", inverse_of: :project
end

app/models/project_user.rb
class ProjectUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  delegate :name, :abbreviation, :start_date, :end_date, 
    to: :project, prefix: true, allow_nil: true
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :user_skills
  has_many :users, through: :user_skills
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :user_teams
  has_many :members, class_name: "User", through: :user_teams, source: :user
  belongs_to :leader, class_name: "User", inverse_of: :team
  accepts_nested_attributes_for :user_teams, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_positions
  has_many :positions, through: :user_positions
  has_many :user_teams
  has_many :teams, through: :user_teams, source: :team
  has_many :user_skills
  has_many :skills, through: :user_skills
  has_many :project_users, -> {order(updated_at: :desc)}
  has_many :projects, through: :project_users
  has_one :team, inverse_of: :leader, foreign_key: "leader_id"
  has_one :project, inverse_of: :leader
end

app/models/user_position.rb
class UserPosition < ActiveRecord::Base
  belongs_to :user
  belongs_to :position
end

app/models/user_skill.rb
class UserSkill < ActiveRecord::Base
  belongs_to :user
  belongs_to :skill
end

app/models/user_team.rb
class UserTeam < ActiveRecord::Base
  belongs_to :user
  belongs_to :team
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    if Settings.activity.personal == params[:page_info]
      @activities = Activity.find_by user: current_user
      @activities.paginate page: params[:page] unless @activities.nil?
    else
      @activities = Activity.all.paginate page: params[:page]
    end
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController 
  def show
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::AdminController
  def index
    @project = Project.new
    @teams = Team.all
  end

  def new
    @project = Project.new
  end

  def create
    if request.xhr?
      unless params[:is_submit] == false
        @project = Project.new project_params
        @project.members = @project.team.members unless @project.team.nil?
        if @project.save
          render json: @project
        else
          render json: @project.errors, status: :unprocessable_entity
        end
      else
        @members = Team.find_by(id: params[:team_id]).members
        render json: @members
        return
      end
    end
  end

  private
  def project_params
    params.require(:project).permit :id, :name, :abbreviation, :start_date,
                                    :end_date, :leader_id, :team_id
  end
end

app/controllers/admin/skills_controller.rb
class Admin::SkillsController < Admin::AdminController
  def index
    @skills = Skill.paginate page: params[:page]
  end

  def create
    @skill = Skill.create skill_params
    if @skill.save
      render json: @skill
    else
      render :new
    end
  end

  def update
    @skill = Skill.find params[:id]
    if @skill.update_attributes skill_params
      render json: @skill
    else
      render :edit
    end
  end

  def destroy
    Skill.find(params[:id]).destroy
    head :no_content
  end

  private
  def skill_params
    params.require(:skill).permit :name
  end
end

app/controllers/admin/teams_controller.rb
class Admin::TeamsController < Admin::AdminController
  def index
    @teams = Team.all
    @users = User.all
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.create team_params
    if @team.save
      render json: @team
    else
      render :new
    end
  end

  private
  def team_params
    params.require(:team).permit :id, :name, :description, :leader_id,
                                  member_ids: []
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  before_action :getUser, only: [:update, :show]

  def index
    @users = User.paginate page: params[:page],
                           per_page: Settings.user.users_number_per_page
  end

  def show
    @team = @user.teams.last
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create user_params
    if @user.save
      render json: @user
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      render json: @user
    else
      render "edit"
    end
  end

  def destroy
    User.find(params[:id]).destroy
    head :no_content
  end

  private
  def user_params
    params.require(:user).permit :name, :role
  end

  def getUser
    @user = User.find params[:id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password,
                                              :password_confirmation, :role)}
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all.paginate page: params[:page], 
      per_page: Settings.team.teams_number_per_page
  end

  def show
    @team = Team.find params[:id]
    @members = @team.members.paginate page: params[:page], 
      per_page: Settings.team.teams_number_per_page
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find params[:id]
    @team = @user.teams.last
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title page_title = ''
    base_title = t("site_name")
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/team_helper.rb
module TeamHelper
  def get_navigation_class link_name, page_param
    if (page_param.nil? && link_name == Settings.team.basic) || page_param == link_name
      "active"
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
  def get_navigation_class link_name, page_param
    if (page_param.nil? && link_name == t("user.basic")) || page_param == link_name
      "active"
    end
  end

  def get_row_class_of_table project_user
    if project_user.status == Settings.project.status.doing
      "active"
    end
  end
end

app/views/admin/users/index.html.erb
<div class="UsersAction">
  <%= will_paginate %>
  <%= react_component "AdminEdit", {data: @users} %>
  <%= will_paginate %>
</div>

app/views/users/_basic.html.erb
<table class="table col-md-6">
  <tr>
    <td><%= t("user.name") %></td>
    <td><%= @user.name %></td>
  </tr>
  <tr>
    <td><%= t("user.email") %></td>
    <td><%= @user.email %></td>
  </tr>
  <tr>
    <td><%= t("user.role") %></td>
    <td><%=
      if @user.role.nil?
        t("user.not_set")
      else
        @user.role
      end
    %></td>
  </tr>
  <tr>
    <td><%= t("user.birthday") %></td>
    <td><%=
      if @user.birthday.nil?
        t("not_set")
      else 
        @user.birthday
      end
    %></td>
  </tr>
  <tr>
    <td><%= t("user.team") %></td>
    <td><%=
      if @team.nil?
        t("not_set")
      else
        @team.name
      end
    %></td>
  </tr>
</table>

app/views/users/_projects.html.erb
<table class="table">
  <thead>
    <tr>
      <th><%= t("name") %></th>
      <th><%= t("abbreviation") %></th>
      <th><%= t("start_date") %></th>
      <th><%= t("end_date") %></th>
      <th><%= t("project.status") %></th>
    </tr>
  </thead>
  <tbody>
    <% if @user.projects.empty? %>
      <tr>
        <td><%= t("project.empty") %></td>
      </tr>
    <% else %>
      <% @user.project_users.each do |project_user| %>
        <tr class="<%= get_row_class_of_table project_user %>">
          <td><%= link_to project_user.project_name, project_path(project_user.project) %></td>
          <td><%= project_user.project_abbreviation %></td>
          <td><%= project_user.project_start_date %></td>
          <td><%= project_user.project_end_date %></td>
          <td><%= project_user.status %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/users/_skill.html.erb
<table class="table col-md-6">
  <thead>
    <tr>
      <th><%= t("name") %></th>
      <th><%= t("skill.level") %></th>
      <th><%= t("skill.used_years") %></th>
    </tr>
  </thead>
  <tbody>
    <% if @user.user_skills.empty? %>
      <tr>
        <td><%= t("skill.empty") %></td>
      </tr>
    <% else %>
      <% @user.user_skills.each do |us| %>
        <tr>
          <td><%= us.skill.name %></td>
          <td><%= us.level %></td>
          <td><%= us.used_years %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<% provide :title, t("user.edit_title") %>
<h1><%= t "user.edit_title" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit t("user.edit_save"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="col-md-12">
  <div id="user-info-navigation" class="col-md-3">
    <ul class="nav nav-pills nav-stacked">
      <li class="<%= get_navigation_class t("user.basic"), params[:page] %>">
        <%= link_to t("user.basic"), user_path(@user) %>
      </li>
      <li class="<%= get_navigation_class t("user.skill"), params[:page] %>">
        <%= link_to t("user.skill"), user_path(@user, page: t("user.skill")) %>
      </li>
      <li class="<%= get_navigation_class t("user.projects"), params[:page] %>">
        <%= link_to t("user.projects"), user_path(@user, page: t("user.projects")) %>
      </li>
      <li class="<%= get_navigation_class t("user.edit"), params[:page] %>">
        <%= link_to t("user.edit"), edit_user_path(@user) %>
      </li>
    </ul>
  </div>
  <div class="col-md-9">
    <% if params[:page] == t("user.skill") %>
      <%= render "skill" %>
    <% elsif params[:page] == t("user.projects") %>
      <%= render "projects" %>
    <% else %>
      <%= render "basic" %>
    <% end %>
  </div>
</div>